name: Pull Request
on: pull_request

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598
        with:
          version: 8.6.7

      - name: Run Tests
        run: |
          pnpm install
          pnpm test
